export const MOVIE_LIST_REQUEST = "MOVIE_LIST_REQUEST";
export const MOVIE_LIST_SUCCESS = "MOVIE_LIST_SUCCESS";
export const MOVIE_LIST_FAILURE = "MOVIE_LIST_FAILURE";
export const MOVIE_LIST_RESPONSE = "MOVIE_LIST_RESPONSE";
export const SEARCH_MOVIE = "SEARCH_MOVIE";
export const UPCOMING_MOVIES_REQUEST = "UPCOMING_MOVIES_REQUEST";
export const UPCOMING_MOVIES_RESPONSE = "UPCOMING_MOVIES_RESPONSE";
