export const SEAT_LAYOUT_REQUEST = "SEAT_LAYOUT_REQUEST";
export const SEAT_LAYOUT_SUCCESS = "SEAT_LAYOUT_SUCCESS";
export const SEAT_LAYOUT_FAILURE = "SEAT_LAYOUT_FAILURE";
export const SHOW_TIMES_REQUEST = "SHOW_TIMES_REQUEST";
export const SHOW_TIMES_RESPONSE = "SHOW_TIMES_RESPONSE";
export const RESERVE_BLOCK_SEAT = "RESERVE_BLOCK_SEAT";
export const RESERVE_BLOCK_SEAT_RESPONSE = "RESERVE_BLOCK_SEAT_RESPONSE";