export const BOOKING_LIST_REQUEST = "BOOKING_LIST_REQUEST";
export const BOOKING_LIST_RESPONSE = "BOOKING_LIST_RESPONSE";
export const CANCEL_TICKET_REQUEST = "CANCEL_TICKET_REQUEST";
export const CANCEL_TICKET_RESPONSE = "CANCEL_TICKET_RESPONSE";
