export const MOVIE_SHOWS_REQUEST = "MOVIE_SHOWS_REQUEST";
export const MOVIE_SHOWS_SUCCESS = "MOVIE_SHOWS_SUCCESS";
export const MOVIE_SHOWS_FAILURE = "MOVIE_SHOWS_FAILURE";
export const MOVIE_DATE_REQUEST = "MOVIE_DATE_REQUEST";
export const MOVIE_DATE_RESPONSE = "MOVIE_DATE_RESPONSE";
//Time Slot
export const TIME_SLOT_REQUEST = "TIME_SLOT_REQUEST";
export const TIME_SLOT_RESPONSE = "TIME_SLOT_RESPONSE";
// Cinema List
export const CINEMAS_LIST_REQUEST = "CINEMAS_LIST_REQUEST";
export const CINEMAS_LIST_RESPONSE = "CINEMAS_LIST_RESPONSE";
// Experiences
export const EXPERIENCE_LIST_REQUEST = "EXPERIENCE_LIST_REQUEST";
export const EXPERIENCE_LIST_RESPONSE = "EXPERIENCE_LIST_RESPONSE";
//Schedule Booking
export const SCHEDULE_BOOKING_REQUEST = "SCHEDULE_BOOKING_REQUEST";
export const SCHEDULE_BOOKING_RESPONSE = "SCHEDULE_BOOKING_RESPONSE";