export const CINEMAS_LIST_REQUEST = "CINEMAS_LIST_REQUEST";
export const CINEMAS_LIST_RESPONSE = "CINEMAS_LIST_RESPONSE";
export const SEARCH_CINEMAS = "SEARCH_CINEMAS";
export const VENUE_DATES_REQUEST = "VENUE_DATES_REQUEST";
export const VENUE_DATES_RESPONSE = "VENUE_DATES_RESPONSE";
export const SHOW_TIME_REQUEST = "SHOW_TIME_REQUEST";
export const SHOW_TIME_RESPONSE = "SHOW_TIME_RESPONSE";
