export const SEND_OTP = "SEND_OTP";
export const SEND_OTP_RESPONSE = "SEND_OTP_RESPONSE";
export const SUBMIT_OTP = "SUBMIT_OTP";
export const SUBMIT_OTP_RESPONSE = "SUBMIT_OTP_RESPONSE";
export const SET_AUTHENTICATION = "SET_AUTHENTICATION";
export const CLEAR_LOGIN = "CLEAR_LOGIN";
